# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionjuegos', '0002_consola_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('fechaLanzamiento', models.CharField(max_length=4)),
                ('desarrolladora', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('especificacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='rooms',
        ),
        migrations.AlterField(
            model_name='consola',
            name='marca',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='consola',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='consola',
            name='version',
            field=models.CharField(max_length=30),
        ),
    ]
