# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionjuegos', '0004_room_consola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
